version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd frontend && yarn dev"
    ports:
      - "3000:3000"
