version: "3"
services:
    frontend2:
       ports:
         - "3000:3000"
       build: ./frontend
       container_name: 'frontend2'
       volumes:
         - ./frontend:/tmp/frontend
         - /tmp/frontend/node_modules/
       stdin_open: true
       tty: true
       command: >
         bash -c "cd ../frontend && npm run dev"